### ISSUE TITLE
Location Assert not working

### ISSUE THREAD

**Issue by derjohn** [helium/wallet-app#310]
Hello,
I am trying to assert locations for two miners for weeks now. One the miners never had a location (location "null", but onboarding has been done before solana migration), the other one was working and had a location.

I tried to se the location with:
- Helium App
- Nebra App
- Hotspotty Connect

All seem to construct a more less less reasonable (some construct wrong antenna height) transaction in the wallet, the black wallet asks me for confirmation and I get "success" messages from the apps. I have > 1M DC in the Wallet and Solana (0.09). But: I can't see any transaction nor does the location assert work.

I am using wallet 2.0.7. I can remember I had one location change working, but that was before Wallet 2.0.6. (dunno remember what version it was).

Can anyone help me?

rgds,
derjohn

**Comment by zaferbozyer** [comment]
Same problem here. I have 3 hotspot in my wallet. All of them onboarded to Helium Network 1 years ago. Also their locations were updated at 14th April 2023 ( 5 days before the Solana Migration). However, after the solana migration, my devices did not show up in the new explorer page. After the Solana migration, the location information of my devices disappeared. It looks as if the devices have never been asserted to an address before. When I try to update the location again, it seems to be onboarding the device to the network for the first time. But they are onboarded 1 year ago... 

Please check the screenshots below. First one is my Helium hotspot (Blue ) app screenshot, second one is my friends helium app screen. The location informations are missing in my screen...
![wallet](https://github.com/helium/wallet-app/assets/39609750/c0a3aed1-be3e-46ae-af01-e041f3a006d1)

Now, I cannot update the location and antenna gain values. But devices are mining IOT Tokens and all of them are fully operational. I just can not assert them to new locations. I claim that those who do not see the location information of the hotspots in the helium Hotspot App, like me, will be unable to update their addresses no matter what brand hotspot they have. Because the mobile apps of hotspot brands receive information from helium wallet or helium hotspot app. As a result, every app is linked to the first app, helium hotspot (blue). I had previously updated the location with the maker applications of the Sensecap and Linxdot brands. None of them worked after Solana migration.

Also, please watch the video in this link. After performing all the steps in the Nebra application and switching to the Helium application, the "confirm" button does not work! I cannot press the "confirm" button in the Helium Wallet application. How could this be related to Nebra? If i can press it, the location will be update. https://drive.google.com/file/d/1c7nANMk2sRVXuLFSEMLGGx2N6qejWCiw/view

**Comment by derjohn** [comment]
As discussed with @waveform  and @nosmaster89 on discord:

If you look at the transaction on https://solscan.io  you will find that solana transaction IS succdessful, e.g. https://solscan.io/tx/2RzrdSdUFhDbVszTfBqh2G8i9g24FrAe3GUwF7LscGVaCSbum4mYrT6SK6RjVbpow269N4eUA1R5iQwzidJivQyd

This transaction is neither shown in black wallet (Issue #1) nor doing what it should do.

In discord they concluded "The hotspots are possibly not properly on chain".

**Comment by derjohn** [comment]
It's solved! Location assert works using the Nebra Maker App. Nebra as well as black wallet have fixed the hotspots asserts list and assertion works \o/\o/\o/.

Actually I had two different issues, the other one was, that the first assert is payed by the maker wallet. It's not prepayed, so the maker wallet has to have
a) 5M DC (assertion costs have been lowered, this is also true for the cost of the 1st assert) b) Some SOL

As conelcom/controllino and syncrobit have empty wallets due to "business trouble", I solved my issue by swapping 5M DC AND some SOL to the Controllino Maker wallet. (You can do everything with the black wallet).

For those, who have the same issue:
Controllino Maker Wallet Solana Address  GSfvrKxBSmU31yEjG1H1Eo6ubTmEVePiRNUDJzLHtr39

See: https://explorer.solana.com/address/GSfvrKxBSmU31yEjG1H1Eo6ubTmEVePiRNUDJzLHtr39/tokens

P.S. This only works , if the hotspot was already onboarded, but never location asserted. If you need initial on-boarding for controllino or syncrobit, please contact the Nebra Support.
