### ISSUE TITLE
insufficient-funds-notification

### ISSUE THREAD

**Issue by ilovespectra** [helium/wallet-app#434]
**Feature Request:

Insufficient funds notification upon transaction simulation**

Currently the app attempts transactions without sufficient SOL, and does not fail-out with any notification, and rather loops the approval request until the user cancels. 

It'd be smoother if you couldn't even try the transaction without the funds required, and it display the amount of SOL needed to the user 

or, if you could attempt it without sufficient funds, that you'd get a notification you have insufficient SOL to fund the transaction, and it display the amount of SOL needed to the user then

or, if the transaction does try to process, it should cancel on it's own after one attempt, and now it display an insufficient funds notification and the amount of SOL needed to the user

**Comment by EdBallou** [comment]
In addition to this, if you try to do swap to get the funds necessary then the new priority fee screen comes under (in z-order) the the approval screen for the swap. If you cancel out of the claim, then you can finally approve the swap but it continues to go in the loop. It might be confused because the claim was just canceled.

**Comment by ChewingGlass** [comment]
This should be supported in the new transaction simulation screen.
